version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11-browsers

    steps:
      - checkout
      - restore_cache:
          key: v1-package-{{ checksum "package.json" }}
      - run: curl -ks -u$ARTIFACTORY_USER:$ARTIFACTORY_PASS "https://d2lartifacts.artifactoryonline.com/d2lartifacts/api/npm/npm-local/auth/d2l" -o .npmrc
      - run: npm install
      - run: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-package-{{ checksum "package.json" }}

workflows:
  version: 2

  build-and-publish:
    jobs:
      - build:
          context: ci-read
